name: nj3
on:
  schedule:
    - cron: '0 7-15,21 * * *'

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  robot_test:
    name: Robot Framework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Nj vapaat
        uses: tarathep/robotframework-github-action@v1.0
        with:
          image: ppodgorsek/robot-framework
          tests_dir: '${{ github.workspace }}/robot_tests'
          reports_dir: '${{ github.workspace }}/robot_tests/reports'
