name: nj3
on:
  schedule:
    - cron: '0 7-15,21 * * *'

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  cache_container_image:
    name: Cache Container Images Action
    uses: jamesmortensen/cache-container-images-action@v1.0.1
    with:
      # Container runtime engine
      runtime: # optional, default is podman
      # Container images to pull and cache
      images: ppodgorsek/robot-framework
          
  robot_test:
    name: Robot Framework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Nj vapaat
        uses: tarathep/robotframework-github-action@v1.0
        with:
          image: ppodgorsek/robot-framework
          tests_dir: '${{ github.workspace }}/robot_tests'
          reports_dir: '${{ github.workspace }}/robot_tests/reports'
