name: nj3
on:
  schedule:
    - cron: '0 7-15,21 * * *'

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  robot_test:
    name: Robot Framework
    runs-on: ubuntu-latest
    steps:
      - name: Nj vapaat
        uses: GoleeTeam/robotframework-browser-action@v1.0-golee1
        with:
          tests_dir: '${{ github.workspace }}/robot_tests'
          reports_dir: '${{ github.workspace }}/output'
