name: nj3
on:
  schedule:
    - cron: '0 7-15,21 * * *'

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  cache_container_image:
    name: Cache Container Images Action
    runs-on: ubuntu-latest
    steps:
      - name: Cache Container Images
        uses: jamesmortensen/cache-container-images-action@v1.0.1
        with:
          # Container images to pull and cache
          images: ppodgorsek/robot-framework

  robot_test:
    name: Robot Framework Browser Run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Nj vapaat
        uses: tarathep/robotframework-github-action@v1.0
        with:
          image: ppodgorsek/robot-framework
          tests_dir: '${{ github.workspace }}/robot_tests'
          reports_dir: '${{ github.workspace }}/output'

      - name: list our images
        run: ls -la ${{ github.workspace }}/output
        
      - name: copy our images
        run: |
          mkdir -pv img
          cp -v ${{ github.workspace }}/output/*.png img/

      - name: tree view 1
        run: tree ${{ github.workspace }}

      # upload the artifact:
      - uses: int128/upload-artifact-wiki-action@v1
        id: upload-artifact-wiki-action
        with:
          path: img/Huslab_Nurmijarvi.png

      # post a comment with it
      - uses: int128/comment-action@v1
        with:
          update-if-exists: replace
          post: |
            ## Screenshot
            <img width="1920" src="${{ steps.upload-artifact-wiki.outputs.url }}/Huslab_Nurmijarvi.png">

      - name: tree view 2
        run: tree ${{ github.workspace }}
