jobs:
  robot_test:
    runs-on: ubuntu-latest
    - name: Robot Framework
      uses: tarathep/robotframework-github-action@v1.0
      with:
        image: kietara/robot-framework
        image_version: 1.0
        tests_dir: '${{ github.workspace }}/robot_tests'
        reports_dir: '${{ github.workspace }}/output'
