name: nj3
on:
  schedule:
    - cron: '0 7-15,21 * * *'

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  cache_container_image:
    name: Cache Container Images Action
    runs-on: ubuntu-latest
    steps:
      - name: Cache Container Images
        uses: jamesmortensen/cache-container-images-action@v1.0.1
        with:
          # Container images to pull and cache
          images: ppodgorsek/robot-framework

  robot_test:
    name: Robot Framework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Nj vapaat
        uses: tarathep/robotframework-github-action@v1.0
        with:
          image: ppodgorsek/robot-framework
          tests_dir: '${{ github.workspace }}/robot_tests'
          reports_dir: '${{ github.workspace }}/output'

      - name: list our images
        run: ls -la ${{ github.workspace }}/output
        
      - name: copy our images
        run: |
          mkdir -pv img
          cp -v ${{ github.workspace }}/output/*.png img/

      - name: add to main
        uses: actions4git/add-commit-push@v1.0.0
        with:
            # Additional path specifiers to be passed to 'git add'. These can be files, folders, globs, or even some fancy Git pathspec things such as ':!ignoreme.txt'. Check out the CSS-Tricks Git Pathspecs and How to Use Them article for the highlights of Git pathspecs. If this input is not specified, 'git add --all' will be used instead. Specifying '.' has slightly different behaviour from '--all'.
            add-pathspec: img/*.png

      # upload the artifact:
      - uses: int128/upload-artifact-wiki-action@v1
        id: upload-artifact-wiki-action
        with:
          path: output/Huslab_Nurmijarvi.png

      # post a comment with it
      - uses: int128/comment-action@v1
        with:
          update-if-exists: replace
          post: |
            ## Screenshot
            <img width="1920" src="${{ steps.upload-artifact-wiki.outputs.url }}/Huslab_Nurmijarvi.png">
